### ISSUE TITLE
Need MCInjector configs error for 1.13.2

### ISSUE THREAD

**Issue by SolDev69** [ThisTestUser/MCPFixer#10]
I followed the tutorial at https://github.com/ThisTestUser/MCPFixer/wiki/Tutorial but got an error saying that it needs mcinjector configs. How do I fix these? where do i get these?

**Comment by ThisTestUser** [comment]
I never got that kind of error, so just make sure you're using MCInjector for 1.13.2 by running "gradlew :1.13.2:projectClientApplyPatches". If it doesn't solve the issue you should upload your error logs.

**Comment by SolDev69** [comment]
I tried recreating but was unable to, might have been an issue with generated jars. I will close this for now unless it shows up again.
