### ISSUE TITLE
Stuck on 'Decompiling'

### ISSUE THREAD

**Issue by ghost** [ThisTestUser/MCPFixer#12]
So, one thing that happened is that whenever I try and run something over 1.15.2+, it just stuck on 'Decompiling'. This never happened in previous versions, any ideas? 

I'm doing 1.16 (with the right mappings, getting those mappings I strongly recommend using MCPReborn just to locate the .jar with the field, methods, params, etc: but, I use this tool because I like it more.)

**Comment by SolDev69** [comment]
This is an issue with MCPConfig. I remember I tried 1.16.3 or 1.16.2 a while ago and it worked, try older MCPConfig commits or my fork. https://github.com/MicherGit/MCPFixer-Config

**Comment by ThisTestUser** [comment]
Also make sure you're not getting the MCP mappings from MCPbot for 1.16 and above. I remember that 1.16.1 worked, although it couldn't recompile immediately because of an issue with Forge mappings.

**Comment by SolDev69** [comment]
Ah, I was getting them from forge for 1.16.x, wasn't sure mcpbot 1.15 mappings would even work.

**Comment by ThisTestUser** [comment]
I looked into this issue more, it looks like at 1.16.5 Forge changed how the TSRGs work, so using MCPConfig from 0cdc6055297f0b30cf3e27e59317f229a30863a6 should decompile 1.16.4 and below successfully (although there may be mapping issues).

**Comment by ThisTestUser** [comment]
I was able to decompile 1.16.4 with no issues, so it's only an issue with 1.16.5 and above. I'll leave #16 open while this error still happens.
