### ISSUE TITLE
I can't decompile minecraft version 1.8.8.

### ISSUE THREAD

**Issue by HistoryParker** [ThisTestUser/MCPFixer#13]
== MCP 9.18 (data: 9.18, client: 1.8.8, server: 1.8.8) ==
"scalac" is not found on the PATH.  Scala files will not be recompiled
# found ff, ff patches, srgs, name csvs, doc csvs, param csvs, astyle, astyle config, rg, ss
Looking in C:\Users\preti\AppData\Roaming\.minecraft\versions for mc installs... OK
Copying assets... OK
Parsing JSON file... OK
Looking for minecraft main jar... Not found
Copying minecraft main jar... OK
> Checking libraries...
        Copying library jinput... OK
        Copying library lwjgl-platform... OK
        Copying library icu4j-core-mojang... OK
        Copying library twitch-external-platform... OK
        Copying library httpcore... OK
        Copying library log4j-api... OK
        Copying library commons-lang3... OK
        Copying library jna... OK
        Copying library libraryjavasound... OK
        Copying library jopt-simple... OK
        Copying library guava... OK
        Copying library oshi-core... OK
        Copying library httpclient... OK
        Copying library commons-compress... OK
        Copying library platform... OK
        Copying library codecjorbis... OK
        Copying library soundsystem... OK
        Copying library librarylwjglopenal... OK
        Copying library lwjgl_util... OK
        Copying library commons-codec... OK
        Copying library jutils... OK
        Copying library commons-logging... OK
        Copying library lwjgl... OK
        Copying library commons-io... OK
        Copying library realms... OK
        Copying library authlib... OK
        Copying library gson... OK
        Copying library netty... OK
        Copying library twitch... OK
        Copying library codecwav... OK
        Copying library twitch-platform... OK
        Copying library jinput-platform... OK
        Copying library log4j-core... OK
        Copying library netty-all... OK
> Checking Natives...
        Extracting native avutil-ttv-51.dll... OK
        Extracting native lwjgl.dll... OK
        Extracting native OpenAL32.dll... OK
        Extracting native jinput-dx8_64.dll... OK
        Extracting native libmfxsw64.dll... OK
        Extracting native jinput-wintab.dll... OK
        Extracting native twitchsdk.dll... OK
        Extracting native jinput-dx8.dll... OK
        Extracting native libmp3lame-ttv.dll... OK
        Extracting native jinput-raw.dll... OK
        Extracting native OpenAL64.dll... OK
        Extracting native jinput-raw_64.dll... OK
        Extracting native swresample-ttv-0.dll... OK
        Extracting native lwjgl64.dll... OK
== Decompiling client using fernflower ==
> Creating SRGs
> Applying SpecialSource
> Applying MCInjector
> Creating renamed srg
> Filtering classes
> Decompiling
'"C:\Program Files\Java\jdk1.8.0_281\bin\java" -jar runtime\bin\fernflower.jar -din=1 -rbr=1 -dgs=1 -asc=1 -rsy=1 -iec=1 -jvn=1 -log=WARN "-e=jars\libraries\net/java/jinput\jinput\2.0.5\jinput-2.0.5.jar" "-e=jars\libraries\org/lwjgl/lwjgl\lwjgl-platform\2.9.4-nightly-20150209\lwjgl-platform-2.9.4-nightly-20150209-natives-windows.jar" "-e=jars\libraries\com/ibm/icu\icu4j-core-mojang\51.2\icu4j-core-mojang-51.2.jar" "-e=jars\libraries\tv/twitch\twitch-external-platform\4.5\twitch-external-platform-4.5-natives-windows-64.jar" "-e=jars\libraries\org/apache/httpcomponents\httpcore\4.3.2\httpcore-4.3.2.jar" "-e=jars\libraries\org/apache/logging/log4j\log4j-api\2.0-beta9\log4j-api-2.0-beta9.jar" "-e=jars\libraries\org/apache/commons\commons-lang3\3.3.2\commons-lang3-3.3.2.jar" "-e=jars\libraries\net/java/dev/jna\jna\3.4.0\jna-3.4.0.jar" "-e=jars\libraries\com/paulscode\libraryjavasound\20101123\libraryjavasound-20101123.jar" "-e=jars\libraries\net/sf/jopt-simple\jopt-simple\4.6\jopt-simple-4.6.jar" "-e=jars\libraries\com/google/guava\guava\17.0\guava-17.0.jar" "-e=jars\libraries\oshi-project\oshi-core\1.1\oshi-core-1.1.jar" "-e=jars\libraries\org/apache/httpcomponents\httpclient\4.3.3\httpclient-4.3.3.jar" "-e=jars\libraries\org/apache/commons\commons-compress\1.8.1\commons-compress-1.8.1.jar" "-e=jars\libraries\net/java/dev/jna\platform\3.4.0\platform-3.4.0.jar" "-e=jars\libraries\com/paulscode\codecjorbis\20101023\codecjorbis-20101023.jar" "-e=jars\libraries\com/paulscode\soundsystem\20120107\soundsystem-20120107.jar" "-e=jars\libraries\com/paulscode\librarylwjglopenal\20100824\librarylwjglopenal-20100824.jar" "-e=jars\libraries\org/lwjgl/lwjgl\lwjgl_util\2.9.4-nightly-20150209\lwjgl_util-2.9.4-nightly-20150209.jar" "-e=jars\libraries\commons-codec\commons-codec\1.9\commons-codec-1.9.jar" "-e=jars\libraries\net/java/jutils\jutils\1.0.0\jutils-1.0.0.jar" "-e=jars\libraries\commons-logging\commons-logging\1.1.3\commons-logging-1.1.3.jar" "-e=jars\libraries\org/lwjgl/lwjgl\lwjgl\2.9.4-nightly-20150209\lwjgl-2.9.4-nightly-20150209.jar" "-e=jars\libraries\commons-io\commons-io\2.4\commons-io-2.4.jar" "-e=jars\libraries\com/mojang\realms\1.7.39\realms-1.7.39.jar" "-e=jars\libraries\com/mojang\authlib\1.5.21\authlib-1.5.21.jar" "-e=jars\libraries\com/google/code/gson\gson\2.2.4\gson-2.2.4.jar" "-e=jars\libraries\com/mojang\netty\1.6\netty-1.6.jar" "-e=jars\libraries\tv/twitch\twitch\6.5\twitch-6.5.jar" "-e=jars\libraries\com/paulscode\codecwav\20101023\codecwav-20101023.jar" "-e=jars\libraries\tv/twitch\twitch-platform\6.5\twitch-platform-6.5-natives-windows-64.jar" "-e=jars\libraries\net/java/jinput\jinput-platform\2.0.5\jinput-platform-2.0.5-natives-windows.jar" "-e=jars\libraries\org/apache/logging/log4j\log4j-core\2.0-beta9\log4j-core-2.0-beta9.jar" "-e=jars\libraries\io/netty\netty-all\4.0.23.Final\netty-all-4.0.23.Final.jar" temp/minecraft_ff_in.jar temp\src\minecraft' failed : 1
Decompile failed
Pressione qualquer tecla para continuar. . .

**Comment by ThisTestUser** [comment]
You don't need to use this for 1.8.8. Same as #5.
