### ISSUE TITLE
No longer applies patches properly if using MCPConfig commit e829c044aec47989a5bbef2def1de40bd89d60ae or higher.

### ISSUE THREAD

**Issue by SolDev69** [ThisTestUser/MCPFixer#14]
For some reason using normal MCPConfig doesn't work, as hunk apply fails and recompile errors. For now I have created a fork at https://github.com/MicherGit/MCPFixer-Config with code from commit 0cdc6055297f0b30cf3e27e59317f229a30863a6 that can be used instead. This seems to be mappings related as in commit e829c04 the forge guys changed how MCPConfig applies mappings and is still broken.

**Comment by ThisTestUser** [comment]
I edited the wiki to use the older MCPConfig, marking as resolved.
