### ISSUE TITLE
No longer works on 1.17+

### ISSUE THREAD

**Issue by SolDev69** [ThisTestUser/MCPFixer#16]
For some reason, even when using MCP mappings, it doesn't work on 1.16 and above, it gets stuck in an endless decompiling loop, and in 1.17 due to forge ditching og mapping system half the files needed in the tutorial don't exist anymore

**Comment by PercyDan54** [comment]
Use https://github.com/Hexeption/MCP-Reborn

**Comment by ThisTestUser** [comment]
MCPFixer still works for 1.16.5 and under.  If you got that error, it might be because you used the wrong libraries (MCPInjector should be a fatjar) or you're not using the correct MCP mappings.

**Comment by ThisTestUser** [comment]
This guide has been updated to support 1.17 and above.
