### ISSUE TITLE
MCP [1.8.8] Cannot decompile both Client and Server

### ISSUE THREAD

**Issue by Prasid12** [ThisTestUser/MCPFixer#17]
i m having this err can anyone help
== MCP 9.18 (data: 9.18, client: 1.8.8, server: 1.8.8) ==
> Searching for javac.exe in C:\Program Files\Java\jre1.8.0_301
> Searching for javac.exe in C:\Program Files
> Searching for javac.exe in C:\Program Files (x86)
"scalac" is not found on the PATH.  Scala files will not be recompiled
!! Can not find client bins !!
Press any key to continue . . .

**Comment by ThisTestUser** [comment]
See #5. You are not supposed to use this with 1.8.8.
