### ISSUE TITLE
1.19 fails on netty-transport-native-epoll

### ISSUE THREAD

**Issue by ghost** [ThisTestUser/MCPFixer#18]
When decompiling 1.19, I followed every step but I still have the same outcome everytime:

> > Checking libraries...
>         Copying library netty-resolver... OK
>         Copying library jna-platform... OK
>         Copying library httpcore... OK
>         Copying library log4j-api... OK
>         Copying library netty-buffer... OK
>         Copying library jna... OK
>         Copying library jopt-simple... OK
>         Copying library text2speech... OK
>         Copying library datafixerupper... OK
>         Copying library guava... OK
>         Copying library oshi-core... OK
>         Copying library netty-handler... OK
>         Copying library lwjgl-stb... OK
>         Copying library commons-logging... OK
>         Copying library commons-compress... OK
>         Copying library fastutil... OK
>         Copying library failureaccess... OK
>         Copying library lwjgl-tinyfd... OK
>         Copying library javabridge... OK
>         Copying library netty-transport-classes-epoll... OK
>         Copying library slf4j-api... OK
>         Copying library commons-codec... OK
>         Copying library httpclient... OK
>         Copying library patchy... OK
>         Copying library lwjgl-opengl... OK
>         Copying library log4j-slf4j18-impl... OK
>         Copying library netty-transport-native-epoll... Error copying library netty-transport-native-epoll
>

**Comment by ThisTestUser** [comment]
I've never seen this error before, but you should try to run 1.19 again (to ensure the libraries are downloaded) or copying the library manually from ```MCPConfig\build\libraries\io\netty\netty-transport-native-epoll```.
