### ISSUE TITLE
Game really doesn't like decompiling 1.16.x

### ISSUE THREAD

**Issue by SolDev69** [ThisTestUser/MCPFixer#22]
1.16.5 gets stuck here
![image](https://github.com/ThisTestUser/MCPFixer/assets/40839581/0c601ce3-f8c1-4826-8bf8-11f253c59f8b)
The last version that I know works is either 1.16.1 or 1.15.2, but I think 1.15.2. Maybe fernflower is too new?

**Comment by ThisTestUser** [comment]
I have successfully decompiled every major version (1.13.2, 1.14.4, 1.15.2, etc) all the way up to 1.19.4. Are you sure you selected the right fernflower version? It doesn't have to be the version shown on the wiki.
